use project;
CREATE TABLE Users( 
id MEDIUMINT NOT NULL AUTO_INCREMENT,
       EMAIL CHAR(255), 
        PASS INT,PRIMARY KEY (id)
); 

INSERT INTO Users (EMAIL,PASS) VALUES('ACU@EGY',123456);
SELECT *FROM Users;